language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: vPDaCATXvuACXLEKxgFH4vANFsuxKgLqzBEpf7WNrgzrtQZCBZr7ho/FT+YqLPrXI1b6hEN7+Ihjrz/hb5AV7drRc91KJzGEBQyjy6lkMci3FeESYdpieTCJ/V32BFJdJoe0MwBFPpJxamp24Ikae8S8NYlCAybYBeTyaUDOu6mtjOKLXqmZdJInhaxZ53Q5vxTV1L48X/b0X8ORNaaBs35RM9dHjCf6N+PLGsJf6mjYmdSCRZNfMNINXr5fCgLVU2kr2kqLv+/hYAzC9I9CoME2jN4t3xjCl/CGjO/CVnC31QJ9WA4qF5ehBdGOXRqyq0MBHEh/m1k+AvE+cGI+vM4zjwB58lZzL5Dtuw8sa2vRzlnvpZmekxIplL/S7hNTV5TN/O5nXXaKQOlAB7N2B6mMhrAeWwtgI619ypO4ey7QO4a+U2i/BlPluXmor+AgkF6/rHQPnyax4aQ6IYNoHEyguz8WO0Iui13p0/zjFT+spC/orSAf4YO2Ozmet2RmW1al8Z0zB9zuZkWKXoZWr9hUuxC9LBLFgLmylv9T4YtPjD3kRpFumyNZ0H2H3nNv0T6jyFcwr761O7o4XRQdU7n54tJnu/Jdm40okn/IBAyxePG/cE15tUaOq3zATZEDiFEEkf1P8CwOLFf3lZhoU+ChqKN2UCFzlo2jtpq+wR4=
  app: mymdb-sample-new
  on:
    repo: benyang00/mymdb-sample
